### ISSUE TITLE
Issue installing diart on Mac M1 due to hmmlearn error

### ISSUE THREAD

**Issue by Farissoliman** [juanmc2005/diart#162]
Trying to install diart on my Macbook Pro M1, however when I try to install using `pip install diart`, I get this error:
```
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
```
followed by
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
ERROR: Could not build wheels for hmmlearn, which is required to install pyproject.toml-based projects
```

I'd imagine this error is due to the Mac M1 architecture and I'm guessing there may be a compatibility issue since the error occurs when it tries to build wheels for the package. Does anyone know of any work arounds for this or other packages that could be used as a substitute by chance?

**Comment by juanmc2005** [comment]
Hi @Farissoliman, thank you for reporting this problem. Does it produce the same error when you install pyannote separately? This dependency is actually on pyannote's side, it's not required by diart per se.

**Comment by ahmedmoorsy** [comment]
I sloved it by using these commands:

- `python3 -m pip install -e git+https://github.com/hmmlearn/hmmlearn.git#egg=hmmlearn`
- `python3 -m pip install git+https://github.com/Farissoliman/pyannote-audio.git@patch-1`

**Comment by juanmc2005** [comment]
So is this a problem with an old version of hmmlearn? Might be worth opening an issue in pyannote.audio (cc @hbredin)
