### ISSUE TITLE
Client for the websocket server

### ISSUE THREAD

**Issue by ethanzrd** [juanmc2005/diart#164]
### Discussed in https://github.com/juanmc2005/diart/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **funboarder13920** December 16, 2022</sup>
Hello,

I'm trying to use the websocket server for diarization.
I implemented a client as it is not provided. I get an output for the diarization but it is always speaker0.

Here is the js code for my client:
```javascript
// Set up the start and stop buttons.
document.getElementById('start-button').onclick = start;
document.getElementById('stop-button').onclick = stop;

// Global variables to hold the audio stream and the WebSocket connection.
var stream;
var socket;

function b64encode(chunk) {
    // Convert the chunk array to a Float32Array
    const bytes = new Float32Array(chunk).buffer;

    // Encode the bytes as a base64 string
    let encoded = btoa(String.fromCharCode.apply(null, new Uint8Array(bytes)));

    // Return the encoded string as a UTF-8 encoded string
    return decodeURIComponent(encoded);
}


function start() {
    // Disable the start button.
    document.getElementById('start-button').disabled = true;
    // Enable the stop button.
    document.getElementById('stop-button').disabled = false;

    // Get access to the microphone.
    navigator.mediaDevices.getUserMedia({ audio: true }).then(function (s) {
        stream = s;

        // Create a new WebSocket connection.
        socket = new WebSocket('ws://localhost:7007');

        // When the WebSocket connection is open, start sending the audio data.
        socket.onopen = function () {
            var audioContext = new AudioContext();
            var source = audioContext.createMediaStreamSource(stream);
            var processor = audioContext.createScriptProcessor(1024, 1, 1);
            source.connect(processor);
            processor.connect(audioContext.destination);

            processor.onaudioprocess = function (event) {
                var data = event.inputBuffer.getChannelData(0);
                // var dataString = String.fromCharCode.apply(null, new Uint16Array(data));
                console.log("sending")
                socket.send(b64encode(data));
            };
        };

        socket.onmessage = function (e) {
            console.log(e);
        }
    }).catch(function (error) {
        console.error('Error getting microphone input:', error);
    });
}

function stop() {
    // Disable the stop button.
    document.getElementById('stop-button').disabled = true;
    // Enable the start button.
    document.getElementById('start-button').disabled = false;

    // Close the WebSocket connection.
    socket.close();
    // Stop the audio stream.
    stream.getTracks().forEach(function (track) { track.stop(); });
}
```

Do you have the code for the client you used ? I would like to make sure that I got that right before looking anywhere else.

Best,</div>

------------------------------------------------------- NEW ISSUE --------------------------------------------------------

Hey everyone! I used that exact same code for my client to transmit audio back to the server.

I used Juan's article [(Color Your Captions)](https://betterprogramming.pub/color-your-captions-streamlining-live-transcriptions-with-diart-and-openais-whisper-6203350234ef) about real-time diarization with Whisper and just changed the audio source from the microphone one to the WebSocket one. It generated random transcriptions like: "hhhhhhhhh"

How it looks now:

```python
import logging
import traceback
import diart.operators as dops
import rich
import rx.operators as ops
from diart import OnlineSpeakerDiarization, PipelineConfig
from diart.sources import WebSocketAudioSource
from whisper_transcriber import WhisperTranscriber
from utilities import concat, colorize_transcription

config = PipelineConfig(
    duration=5,
    step=0.5,
    latency="min",
    tau_active=0.5,
    rho_update=0.1,
    delta_new=0.57,
)
dia = OnlineSpeakerDiarization(config)
source = WebSocketAudioSource(config.sample_rate, "localhost", 8000)

asr = WhisperTranscriber(model="small")

transcription_duration = 2
batch_size = int(transcription_duration // config.step)
source.stream.pipe(
    dops.rearrange_audio_stream(
        config.duration, config.step, config.sample_rate
    ),
    ops.buffer_with_count(count=batch_size),
    ops.map(dia),
    ops.map(concat),
    ops.filter(lambda ann_wav: ann_wav[0].get_timeline().duration() > 0),
    ops.starmap(asr),
    ops.map(colorize_transcription),
).subscribe(on_next=rich.print, on_error=lambda _: traceback.print_exc())

print("Listening...")
source.read()
```

However, when using diart.client from another Python instance, it does work.

I then modified the transcribe function in the following way to review the segment:

```python
def transcribe(self, waveform):
  print("transcription started")
  """Transcribe audio using Whisper"""
  # Pad/trim audio to fit 30 seconds as required by Whisper
  audio = waveform.data.astype("float32").reshape(-1)
  sf.write("segment.wav", audio, 16000)
  print("file saved")
```

The audio file was super distorted.

When I tested the audio file when using diart.client from the CLI, it was perfect and everything worked just like it should have. I just can't figure out the problem with the client.

Would appreciate any help on the matter!

**Comment by lostz** [comment]
I also have the same needs and encountered the same problem

**Comment by juanmc2005** [comment]
Hi @ethanzrd @lostz, I'm thinking of two possible issues:

### 1. The audio is not encoded correctly

Take a single audio segment and encode it with the JS code, then encode it with `diart.utils.encode_audio`:

```python
def encode_audio(waveform: np.ndarray) -> Text:
    data = waveform.astype(np.float32).tobytes()
    return base64.b64encode(data).decode("utf-8")
```

If the resulting strings don't match, there's a problem in your encoding.

### 2. The audio you capture and send in the client doesn't match the required step/sample rate

If you take a look at the arguments of `diart.client`, you have to specify a step and a sample rate that MUST match the pipeline running remotely. I'm assuming you're using the default values so that would be 0.5s.
This essentially means that each audio block you send to the server has to contain (at 16khz) 0.5 * 16000 = 8000 samples.

If this is the case, then sending the correct number of samples should solve your problem.

On the library side, It's a bit complicated to make this automatic because the server receives only audio without a sample rate.
I've been wanting to modify the server to receive a json object like this:

```json
{
    "audio": "base64 audio string"
    "sample_rate": 16000
}
```

That way the server can automatically process blocks of the correct size. I would be happy to merge this feature if you're up for contributing :-)

**Comment by ethanzrd** [comment]
@juanmc2005 Thank you so much for responding this fast! Can't believe I didn't think about testing with a single segment.

I'll review the sample rate/step once again, and I'll be more than glad to contribute! I'll get to working on it next week and I'll keep you both updated on if I manage to make the app work.

**Comment by ethanzrd** [comment]
Hey @lostz, Juan was right. The problem with this code was that the sample rate nor the block size were set correctly.

**Set the sample rate to the required one:**

The required sample rate is `16000`, you can set it when creating the Audio Context object, here is how this change would be reflected in the sample I provided when opening this issue:

Instead of:
```js
var audioContext = new AudioContext();
```

Use:
```js
var audioContext = new(window.AudioContext || window.webkitAudioContext)({
    sampleRate: MIC_SAMPLE_RATE,
});
```

**Set the block size to the required block size of 8000:**

You can set the block size when creating a script processor for the Audio Context, however, it must be a power of 2. The closest value is 8192 and it worked for me.

In the code sample, instead of:
```js
var processor = audioContext.createScriptProcessor(1024, 1, 1);
```

Use:
```js
var processor = audioContext.createScriptProcessor(8192, 1, 1);
```
