### ISSUE TITLE
Python Sample is not working in Windows 11

### ISSUE THREAD

**Issue by unchaptered** [juanmc2005/diart#167]
Hello, my name is lee-minseok.
I found an interesting repository called diart in the past.
It looks so interesting to me, but I can't execute this code.

Similar Issue : https://github.com/juanmc2005/diart/issues/149

### Code

https://github.com/juanmc2005/diart#from-python

```
from diart import OnlineSpeakerDiarization
from diart.sources import MicrophoneAudioSource
from diart.inference import RealTimeInference
from diart.sinks import RTTMWriter

pipeline = OnlineSpeakerDiarization()
mic = MicrophoneAudioSource(pipeline.config.sample_rate)
inference = RealTimeInference(pipeline, mic, do_plot=True)
inference.attach_observers(RTTMWriter(mic.uri, "/output/file.rttm"))
prediction = inference()
```

### Environment

```
**Windows 11**
```

**Comment by juanmc2005** [comment]
Stale issue. Feel free to re-open if needed
