### ISSUE TITLE
Running diart + Whisper on Raspberry Pi 5

### ISSUE THREAD

**Issue by swm35** [juanmc2005/diart#200]
Dear @juanmc2005

Do you know if anyone has managed to get your code to run diarization with transcriptions (https://betterprogramming.pub/color-your-captions-streamlining-live-transcriptions-with-diart-and-openais-whisper-6203350234ef) working on a Raspberry Pi 5?  I cannot get diart working on the RPi5 as I keep getting a "Segmentation fault" error message, though it seems more promising than the error messages I was getting before on the RPi4.

In Issue #99, there was a discussion about getting diart running on an RPi4, but no final conclusion as far as I can tell.

Kind regards

Simon

**Comment by juanmc2005** [comment]
Hi @swm35, I think diart should fit into RAM on a raspberry pi, but the segmentation fault might be because of loading whisper. Try checking if you can run both diart and whisper separately first and monitor the RAM consumption.

Otherwise, I've recently been working on compatibility with ONNX models so it should be possible to easily quantize diart models in the future too.

**Comment by swm35** [comment]
Hi @juanmc2005

Thank you for your response.  I have not got around to trying Whisper yet, the errors all relate to running diart only so far.

I tried your suggestion of monitoring the RAM usage, using htop and iostat -c 1 (also gdb as a debugger).  As far as I can tell, it does not appear to be a memory limit problem as the available RAM falls to about 70% at the lowest, though all the materials online about "Segmentation fault" do suggest some memory issue.

The full error message I get is shown below, does anything here suggest an obvious solution?  Should I be worried about the references to "Bad things might happen ...."?  I tried reverting to those older packages but that did not resolve the problem.

(diart) pi@pi:~ $ python test_stream.py 
/home/pi/miniforge3/envs/diart/lib/python3.8/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/home/pi/miniforge3/envs/diart/lib/python3.8/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .cache/torch/pyannote/models--pyannote--segmentation/snapshots/2ffce0501d0aecad81b43a06d538186e292d0070/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0. Bad things might happen unless you revert torch to 1.x.
Lightning automatically upgraded your loaded checkpoint from v1.2.7 to v2.1.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .cache/torch/pyannote/models--pyannote--embedding/snapshots/c6335d8f1cd77b30084387468a6cf26fea90009b/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.8.1+cu102, yours is 2.1.0. Bad things might happen unless you revert torch to 1.x.
Streaming input_device:None ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   Segmentation fault

Kind regards

Simon

**Comment by juanmc2005** [comment]
@swm35 the warnings are not the cause of the issue. I also get them without a segmentation fault.
Since you get the progress bar, `StreamingInference` is at least getting to [this line](https://github.com/juanmc2005/diart/blob/main/src/diart/inference.py#L212). Are you running with `do_plot=True`?

Can you debug [this method](https://github.com/juanmc2005/diart/blob/main/src/diart/blocks/diarization.py#L160) line by line until it gives you the segmentation fault? I'm guessing that should point you to the culprit line.

**Comment by swm35** [comment]
Thank you @juanmc2005.  I did the line-by-line debugging which showed the crash happened while executing this line:
segmentations = self.segmentation(batch) # shape (batch, frames, speakers)

This is an instance of the SpeakerSegmentation class imported from diarization.py.  Debugging that shows the crash at:
output = self.model(wave.to(self.device)).cpu()

Does this suggest the crash happened when the model was put onto the CPU?  If so, it seems like a lack of memory on the RPi5.

Kind regards

Simon

**Comment by juanmc2005** [comment]
@swm35 thank you for that valuable info. I suggest you separate that line into:

```python
wave = wave.to(self.device)
output = self.model(wave)
output = output.cpu()
return output
```

Then debug line by line again to see where it crashes. Most probably it will crash when calling the model. If that's the case, try opening the python interpreter and infer a random chunk:

```python
>>> import torch
>>> from pyannote.audio import Model
# I'm guessing this is the model you're using, please double check
>>> model = Model.from_pretrained("pyannote/segmentation")
>>> x = torch.randn(1, 1, 80000)
>>> seg = model(x)
```

If this fails then your problem would be coming from pyannote.audio.

**Comment by swm35** [comment]
Thank you @juanmc2005.  You are right on both counts - expanding the code shows it crashes at the "output = self.model(wave)" line and the subsequent test on a random chunk crashes at the "seg = model(x)" line.  I have also tried reducing the random chunk size from 5 s down to 0.1 s (80,000 to 1,600), but it still gives the segmentation fault.

Does this mean that the pre-trained pyannote/segmentation model is too large for the RPi5 memory?  Should I open this as an issue on the pyannote.audio GitHub site or do I need to look into knowledge distillation to create a smaller model?

Kind regards

Simon

**Comment by juanmc2005** [comment]
@swm35 I suggest you open an issue on pyannote.audio. It could be a matter of model size but I wouldn't be so sure

**Comment by danielrhodes** [comment]
Also seeing this segmentation fault on a Mac using the command line example in the docs:

It happens with the microphone and a wav file and with our without the cpu flag. Using the conda environment setup from the environment.yml

```bash
> KMP_DUPLICATE_LIB_OK='True' diart.stream --cpu test.wav
/Users/<user>/miniforge3/envs/diart/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../.cache/torch/pyannote/models--pyannote--segmentation/snapshots/2ffce0501d0aecad81b43a06d538186e292d0070/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.1. Bad things might happen unless you revert torch to 1.x.
[1]    76616 segmentation fault  KMP_DUPLICATE_LIB_OK='True' diart.stream --cpu
```

What are some things I could do to help get to the bottom of this?

**Comment by juanmc2005** [comment]
Hi @danielrhodes, as I posted previously, I suggest you debug line by line until you arrive to the line that's causing the crash. Once we know which line causes it we can think of what the problem and solution might be.
