### ISSUE TITLE
WeSpeaker model load failed!

### ISSUE THREAD

**Issue by SheenChi** [juanmc2005/diart#223]
hello!
  I want to test wespeaker model performance in the diart stream.py, I set the params like: --embedding pretrained/wespeaker/voxceleb_resnet34_LM.onnx, but when run this demo,  error happens with message:
`_pickle.UnpicklingError: invalid load key, '\x08'.`
 
 I found this problem is caused by PyannoteLoader \__call\__ func can not load onnx model from Model.from_pretrained and not catch UnpicklingError exception, maybe the \__call\__ func should like this:

```
    def __call__(self) -> Callable:
        try:
            model = Model.from_pretrained(self.model_info, use_auth_token=self.hf_token)
            specs = getattr(model, "specifications", None)
            if specs is not None and specs.powerset:
                model = PowersetAdapter(model)
            return model
        except HTTPError:
            pass
        except ModuleNotFoundError:
            pass
        except UnpicklingError:
            pass
        return PretrainedSpeakerEmbedding(self.model_info, use_auth_token=self.hf_token)
```

**Comment by juanmc2005** [comment]
Hi @SheenChi, are you able to load the model using `PretrainedSpeakerEmbedding`? I don't think pyannote can load arbitrary onnx models. In that case, you may want to implement a custom loader (as shown [here](https://github.com/juanmc2005/diart?tab=readme-ov-file#custom-models)) to use `WeSpeakerPretrainedSpeakerEmbedding` (see [here](https://github.com/pyannote/pyannote-audio/blob/db24eb6c60a26804b1f07a6c2b39055716beb852/pyannote/audio/pipelines/speaker_verification.py#L389)).

Alternatively, you could export a custom version of your model to ONNX that can receive both the waveform and speaker weights to give per-speaker embeddings. That way you could simply use `EmbeddingModel.from_pretrained` or `from_onnx` with your new onnx file.

**Comment by SheenChi** [comment]
ok, thank you for your response, i will try it
