### ISSUE TITLE
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'

### ISSUE THREAD

**Issue by realchandan** [juanmc2005/diart#234]
Everytime I try to run `diart.stream -h`

I get `ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'`

Which is coming from `pyannote/core/notebook.py, line 129`

I tried installing without conda, with conda and even building docker image from the Dockerfile [here](https://github.com/juanmc2005/diart/issues/195)

But I still get `ImportError: cannot import name 'get_cmap' from 'matplotlib.cm' (/opt/venv/lib/python3.11/site-packages/matplotlib/cm.py)`

I think some recent dependency change broke this whole thing.

**Comment by juanmc2005** [comment]
Hi @realchandan thank you for reporting this! I'll address the compatibility issue for the next release

**Comment by plischwe** [comment]
I tried 3.8 and that doesn't seem to work. I noticed the traditional cmap functionality works until 3.5.0, I see a deprecation notice in the 3.6.0 release.

**Comment by juanmc2005** [comment]
After some digging, it looks like this is coming from `pyannote.core`. It looks like the error was fixed but never released.
I just opened an issue to ask for a new release with the fix: https://github.com/pyannote/pyannote-core/issues/100

**Comment by juanmc2005** [comment]
I just merged this fix as part of PR #237. Until v0.10 is released, this problem can be solved by installing matplotlib 3.5.x as mentioned above
