### ISSUE TITLE
Paper at JOSS

### ISSUE THREAD

**Issue by juanmc2005** [juanmc2005/diart#98]
Hi @zaouk, @Yagna24, @ckliao-nccu, @igordertigor, @AMITKESARI2000!

I'm planning to submit a paper for diart at [The Journal of Open Source Software (JOSS)](https://joss.theoj.org/) and it seems natural that all of you, as contributors, appear in the list of authors.

Please let me know if you're interested. If you do, I'll let you know about the information I'd need (most certainly name and affiliation).

Thank you again for your valuable contributions!

**Comment by AMITKESARI2000** [comment]
Sure @juanmc2005 !
I'd be bery much glad to be involved (even though my contribution was not that much :') )

**Comment by Yagna24** [comment]
Sure, @juanmc2005 I'll love to appear as a contributor. Thank you for taking the time to consider my minor inputs.

**Comment by zaouk** [comment]
Sure @juanmc2005, I would love to :)

**Comment by juanmc2005** [comment]
For those who are interested, could you please fill [this form](https://docs.google.com/forms/d/e/1FAIpQLSdw0CifeWnbnXGfsS367DY8FEAwXuv9ybTy_Q80z3KgI2OBJA/viewform?usp=sf_link) by the 29th September? I'm planning to submit on the 30th :)

I will soon add the formatted paper in a branch called `joss`. Feel free to make any comments or suggestions!

Thank you!

**Comment by igordertigor** [comment]
Thank you @juanmc2005 , I just came home after parental leave and it seems that I missed the deadline for an (almost) free paper. After all, my contribution was really minimal. However, if you can still add me, let me know and I'll add my information to the form.

**Comment by juanmc2005** [comment]
Hi @igordertigor, yes there's still time. You can fill the form and I'll add you to the list :)

**Comment by igordertigor** [comment]
Ok, I'll send something tomorrow. I need to figure out what I should add as affiliation.

**Comment by igordertigor** [comment]
Response should have been recorded.

**Comment by juanmc2005** [comment]
@igordertigor just added you to the list

**Comment by AMITKESARI2000** [comment]
Hi @juanmc2005 , any update or news about the journal?

**Comment by juanmc2005** [comment]
Hi @AMITKESARI2000, all the information I have is [here](https://github.com/openjournals/joss-reviews/issues/4810)

**Comment by juanmc2005** [comment]
Hello everybody, the paper has finally been accepted. Here's the link: https://joss.theoj.org/papers/10.21105/joss.05266

**Comment by AMITKESARI2000** [comment]
Congratulations to all for the publication!
